version: '3.8'

services:
  # Web Dashboard (React SPA + Nginx Reverse Proxy to API)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - '80'

  # NestJS REST & OpenAPI API Server
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        SCOPE: api
    restart: always
    environment:
      PORT: 4000
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-cron_user}:${POSTGRES_PASSWORD:-cron_secure_pass_2026}@13.206.16.144:5432/${POSTGRES_DB:-cron_saas}
      REDIS_HOST: 13.206.16.144
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_secure_pass_2026}
      FRONTEND_URL: ${FRONTEND_URL:-http://cron-app.13.207.216.68.sslip.io}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-b5e8f498c39d8461719c8fba5a4c9c1b72e90c8831ef09c0d123456789abcdef}
    expose:
      - '4000'
